class_name Pal
extends RefCounted
## The whole art direction lives here. Every colour is a weathered earth
## pigment — ochre, umber, charcoal, bone — the same palette the caves were
## painted with. Nothing is saturated: that is what keeps it from reading as a
## cartoon, and it is what makes the game look like its own subject matter.

const OCHRE := Color("b9772f")
const OCHRE_DARK := Color("8a4b2a")
const OCHRE_DEEP := Color("5e3319")
const CHARCOAL := Color("23201c")
const STONE := Color("8d857a")
const STONE_DARK := Color("5f5850")
const BONE := Color("e8e0cd")
const EMBER := Color("c75a33")
const CAVE_TOP := Color("2c1a12")
const CAVE_BOTTOM := Color("6b3f22")

## Daytime outdoors. Distant things are paler and bluer than near ones — that
## fading is what the eye reads as distance, as much as the parallax speed is.
const SKY_HIGH := Color("7fb0cc")
const SKY_LOW := Color("d8e2de")
const SUN := Color("f6ecc8")
const MTN_FAR := Color("9aa8b3")
const MTN_FAR_RIM := Color("b2bec6")
const SNOW := Color("e7edef")
const MTN_MID := Color("7d8b69")
const MTN_MID_RIM := Color("8d9a77")
const HILL_NEAR := Color("6b7c4a")
const HILL_NEAR_RIM := Color("7a8b54")
const TREE_DARK := Color("44533a")
const GRASS := Color("7a8a4a")
const GRASS_DARK := Color("5a6935")
const DIRT := Color("8a6947")
const DIRT_DARK := Color("694e33")

## Creatures. Each gets a body colour, a darker tone for shade and underside
## parts, and an accent — so they read as drawn animals, not silhouettes.
const OUTLINE := Color("2a211a")
const WASP := Color("c8993e")
const WASP_DARK := Color("8e6924")
const WING := Color("ccd7d7")
const LIZ := Color("75814b")
const LIZ_DARK := Color("515b33")
const LIZ_BELLY := Color("b8bb89")
const EYE_YELLOW := Color("d8b349")
const TRAP_GREEN := Color("697e46")
const TRAP_DARK := Color("495932")
const MAW := Color("9b4f57")
const TOOTH := Color("e5dcc5")
const BOAR_HIDE := Color("69503f")
const BOAR_DARK := Color("443123")
const BOAR_BELLY := Color("8c7257")
const BRISTLE := Color("2e241b")
const HOOF := Color("2e241b")
const TUSK := Color("ddd2b7")
const RUNNER_HIDE := Color("7c6043")
const RUNNER_DARK := Color("533f27")
const ROCK := Color("948e83")
const ROCK_DARK := Color("6a655c")
const ROCK_LIGHT := Color("b1aca0")
const DUST := Color("bca889")
const VINE := Color("6a5535")

## Tropical jungle: layered greens that pale into mist with distance, warm
## cliff stone, and the red-ochre of hands pressed on rock.
const MIST := Color("cfdcd6")
const JUNGLE_FAR := Color("93ab98")
const JUNGLE_MID := Color("607d55")
const JUNGLE_NEAR := Color("445f3c")
const FROND := Color("55764a")
const FROND_LIGHT := Color("6d8f58")
const TRUNK := Color("6a5942")
const TRUNK_DARK := Color("493c2c")
const CLIFF := Color("998a73")
const CLIFF_DARK := Color("77694f")
const CAVE_MOUTH := Color("2a2018")
const PAINT := Color("a9502f")
const GEM := Color("c42b3a")
const GEM_LIGHT := Color("f2828b")
const GEM_DEEP := Color("7d1520")
const TEPUI := Color("8e9a90")
const TEPUI_SHADE := Color("727d75")
const WATER := Color("e8f2f1")
const CANOPY_FAR := Color("88a28b")
const CANOPY_MID := Color("65815b")
const EMERGENT := Color("7c967c")
const BAMBOO := Color("8d9b59")
const BAMBOO_DARK := Color("687445")
const RAY := Color("fff3d2")
const SKULL := Color("d9cfb7")
const FIRE := Color("e2893a")

## Night (Level 2): cold blue against warm firelight. The dark itself is laid
## over the scene by Night, so these are the colours things have when a flame
## or the moon is on them. Nothing here is black: the dark is a deep blue.
const NIGHT_SKY_HIGH := Color("1a2340")
const NIGHT_SKY_LOW := Color("3c4a66")
const DUSK_HIGH := Color("4f5a7a")
const DUSK_LOW := Color("b7876a")
const MOON := Color("eef0e2")
const MOON_SHADE := Color("c9cdbf")
const STAR := Color("d4dcea")
const DARK_TINT := Color("0b1122")
const NIGHT_FAR := Color("56647e")
const NIGHT_FAR_RIM := Color("7c8aa2")
const NIGHT_MID := Color("3e4c5c")
const NIGHT_NEAR := Color("2f3c46")
const PINE := Color("3a4f48")
const PINE_DARK := Color("2b3b37")
const MOONLIT := Color("9fb0c4")
const FLAME := Color("f0a948")
const FLAME_CORE := Color("fbe6a8")
const EMBER_GLOW := Color("e0612f")
const ASH := Color("6a625a")
const HEARTH_STONE := Color("7a7268")
const WOLF := Color("7a7770")
const WOLF_DARK := Color("54524c")
const WOLF_BELLY := Color("a8a294")
const WOLF_EYE := Color("e6d77e")
const BAT := Color("5a4a45")
const BAT_WING := Color("6e5a52")
const HIDE := Color("8e6d4b")
const HIDE_DARK := Color("654c33")
const DEADWOOD := Color("8a7c6a")
const DEADWOOD_DARK := Color("5e5345")

## The mountain and the great tree (Level 2, second half)
const CRAG := Color("7e7a74")
const CRAG_DARK := Color("58554f")
const CRAG_LIGHT := Color("a9a79f")
const MOUNTAIN_FACE := Color("262c35")
const BARK := Color("5d4c3a")
const BARK_DARK := Color("3f3327")
const CANOPY := Color("33493a")
const CANOPY_DARK := Color("27382d")
const MONKEY := Color("7a5a3e")
const MONKEY_DARK := Color("54402c")
const MONKEY_FACE := Color("c9a987")
const BANANA := Color("d9bc4f")
const BANANA_DARK := Color("a88a33")
const WIND := Color("c9d6e4")
