class_name Pal
extends RefCounted
## Level 1 palette: ochre, charcoal, bare rock. Everything is drawn in code,
## so this file is the whole art direction for the prototype.

const OCHRE := Color("c9772f")
const OCHRE_DARK := Color("8a4b2a")
const OCHRE_DEEP := Color("5e3319")
const CHARCOAL := Color("23201c")
const STONE := Color("8d857a")
const STONE_DARK := Color("5f5850")
const BONE := Color("efe6d2")
const EMBER := Color("e0562a")
const CAVE_TOP := Color("2c1a12")
const CAVE_BOTTOM := Color("6b3f22")

## Daytime outdoors. Distant things are paler and bluer than near ones — that
## fading is what the eye reads as distance, as much as the parallax speed is.
const SKY_HIGH := Color("57b6ef")
const SKY_LOW := Color("cfeaf7")
const SUN := Color("fff6cf")
const MTN_FAR := Color("9fb9d4")
const MTN_FAR_RIM := Color("bdd2e6")
const SNOW := Color("f4fbff")
const MTN_MID := Color("7c9f77")
const MTN_MID_RIM := Color("93b489")
const HILL_NEAR := Color("5c8f3c")
const HILL_NEAR_RIM := Color("74ab4c")
const TREE_DARK := Color("2f6b33")
const GRASS := Color("6fae3a")
const GRASS_DARK := Color("4d8526")
const DIRT := Color("8b5a2b")
const DIRT_DARK := Color("6b4420")

## Creatures. Each gets a body colour, a darker tone for shade and underside
## parts, and an accent — so they read as drawn animals, not silhouettes.
const OUTLINE := Color("2b1a10")
const WASP := Color("e8a83c")
const WASP_DARK := Color("a9671a")
const WING := Color("d8eef8")
const LIZ := Color("6f9a3e")
const LIZ_DARK := Color("4a6c27")
const LIZ_BELLY := Color("cbd98d")
const EYE_YELLOW := Color("f2c53d")
const TRAP_GREEN := Color("59a246")
const TRAP_DARK := Color("3b7a31")
const MAW := Color("c4405a")
const TOOTH := Color("f6f0df")
const BOAR_HIDE := Color("6b4a33")
const BOAR_DARK := Color("46301f")
const BOAR_BELLY := Color("9a7554")
const BRISTLE := Color("2e2118")
const HOOF := Color("312218")
const TUSK := Color("efe6d2")
const RUNNER_HIDE := Color("8a5f3a")
const RUNNER_DARK := Color("5b3c23")
const ROCK := Color("9a948a")
const ROCK_DARK := Color("6d675f")
const ROCK_LIGHT := Color("bdb7ab")
const DUST := Color("c4ab86")
const VINE := Color("6b4a22")
